[package]
name = "office-convert-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
axum = { version = "0.7.5", features = ["multipart"] }
axum_typed_multipart = "0.11.2"
bytes = "1.7.1"
dotenvy = "0.15.7"
libreoffice-rs = "0.3"
rand = "0.8.5"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
tempfile = "3.12.0"
thiserror = "1.0.63"
tokio = { version = "1.39.2", features = ["full"] }
tracing = "0.1.40"
