services:
  office_convert_server_1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: office_convert_server_1
    ports:
      - "3000:3000"
  # office_convert_server_2:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: office_convert_server_2
  #   ports:
  #     - "3001:3000"
  # office_convert_server_3:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: office_convert_server_3
  #   ports:
  #     - "3002:3000"
  # office_convert_server_4:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: office_convert_server_4
  #   ports:
  #     - "3003:3000"
  # office_convert_server_5:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: office_convert_server_5
  #   ports:
  #     - "3004:3000"
  # office_convert_server_6:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: office_convert_server_6
  #   ports:
  #     - "3005:3000"
